# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20240613-224954-concentric-sack

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: fr
pipeline:
  - name: WhitespaceTokenizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.99 # make sure to test the confidences of your intents and then specify this value
    fallback_action: "action_fallback" # automatically gets triggered when fallback occurs

policies:
  - name: MemoizationPolicy
  - name: RulePolicy # added alternative to above fallback classifier, you can use any one or both.
    core_fallback_threshold: 0.99 # make sure to test the confidences of your stories, rules and domain and then specify this value
    core_fallback_action_name: action_fallback
    enable_fallback_prediction: true
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
